
server.port: 8082
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: auth-service

spring.datasource:
  url: jdbc:postgresql://ec2-54-87-34-201.compute-1.amazonaws.com:5432/d50mkad3ucr4fr
  username: spfshdsntyvzuw
  password: 6b8b0a2effacf4c2c903ff54c9397f6c4adccfe57b8817d545568ca165998b91
  initialization-mode: always

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.chisom: DEBUG

app:
  eureka-server: localhost

security:
  signing-key: <signing-key>

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:https://reloadly-eureka-server.herokuapp.com/eureka}
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    hostname: localhost

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

auth-server-health: https://reloadly-auth-server.herokuapp.com/actuator/health

---
app:
  eureka-server: eureka

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres/auth_db
    username: postgres
    password: postgres
    initialization-mode: always


server.port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  signing-key: <signing-key>